### ISSUE TITLE
How do I mine?

### ISSUE THREAD

**Issue by codewithmide** [Findiglay/coal-cli#1]
The readme does not provide a comprehensive steps on mining

**Comment by Codeindeed** [comment]
`coal mine` 

to check for help run` coal -h`

**Comment by Findiglay** [comment]
@codewithmide if you've already mined ORE, then to mine COAL you simply need to install the CLI

```
cargo install --git https://github.com/Findiglay/coal-cli.git
coal mine --cores 8
```

**Comment by codewithmide** [comment]
Thank you @Codeindeed and @Findiglay 

I am actively mining now. Where is this listed though?

**Comment by Findiglay** [comment]
@codewithmide check https://coal.digital
